FROM nvcr.io/nvidia/pytorch:22.08-py3 as BASE

ARG USER=user
ARG UID=1000
ARG GID=1000
ARG PW=${USER}

RUN --mount=type=cache,id=apt-dev,target=/var/cache/apt \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        sudo && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -m ${USER} --uid=${UID} -s /bin/bash && echo "${USER}:${PW}" | chpasswd && adduser ${USER} sudo

RUN chown -R ${UID}:${GID} /opt/conda

RUN cp /root/.bashrc /home/${USER}/.bashrc && \
    chown ${UID}:${GID} /home/${USER}/.bashrc

RUN cp -R /root/.pip /home/${USER}/.pip && \
    chown -R ${UID}:${GID} /home/${USER}/.pip

USER ${UID}:${GID}
